server:
  port: 8080
  servlet:
    context-path: /api

config:
  crawl:
    maxUrlNum: 10
    deepLevel: 0
    timeOutSecond: 20

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: info,health,prometheus